export default function apiMusica() {
  return [
    {
      id: 1,
      titulo: "Anjos",
      cantor: "O Rappa",
      capa: require("../assets/images/anjos.png"),
      audio: require("../assets/music/orappa-anjos-instrumental.mp3"),
      letra: require("../assets/lyrics/"),
    },
    {
      id: 2,
      titulo: "Baby",
      cantor: "Justin Bieber",
      capa: require("../assets/images/baby.png"),
      audio: require("../assets/music/justinbieber-baby-instrumental.mp3"),
      letra: require("../assets/lyrics/"),
    },
    {
      id: 3,
      titulo: "Evidências",
      cantor: "Chitaozinho & Xororó",
      capa: require("../assets/images/evidencias.png"),
      audio: require("../assets/music/chitaozinho-e-xororo-evidencias-instrumental.mp3"),
      letra: require("../assets/lyrics/"),
    },
    {
      id: 4,
      titulo: "Gostava Tanto De Você",
      cantor: "Tim Maia",
      capa: require("../assets/images/gostava-tanto-de-voce.png"),
      audio: require("../assets/music/timmaia-gostavatantodevoce-instrumental.mp3"),
      letra: require("../assets/lyrics/"),
    },
    {
      id: 5,
      titulo: "Heaven",
      cantor: "Bryan Adams",
      capa: require("../assets/images/heaven.png"),
      audio: require("../assets/music/bryanadams-heaven-instrumental.mp3"),
      letra: require("../assets/lyrics/"),
    },
    {
      id: 6,
      titulo: "Levo comigo",
      cantor: "RESTART",
      capa: require("../assets/images/levo-comigo.png"),
      audio: require("../assets/music/restart-levocomigo-instrumental.mp3"),
      letra: require("../assets/lyrics/"),
    },
    {
      id: 7,
      titulo: "Mágica",
      cantor: "Calcinha Preta",
      capa: require("../assets/images/magica.png"),
      audio: require("../assets/music/calcinhapreta-magica-instrumental.mp3"),
      letra: require("../assets/lyrics/"),
    },
    {
      id: 8,
      titulo: "Quando a chuva passar",
      cantor: "Ivete Sangalo",
      capa: require("../assets/images/quando-a-chuva-passar.png"),
      audio: require("../assets/music/ivetesangalo-quandoachuvapassar-instrumental.mp3"),
      letra: require("../assets/lyrics/"),
    },
    {
      id: 9,
      titulo: "Sailor Song",
      cantor: "Gigi Perez",
      capa: require("../assets/images/sailor-song.png"),
      audio: require("../assets/music/gigiperez-sailorsong-instrumental.mp3"),
      letra: require("../assets/lyrics/"),
    },
    {
      id: 10,
      titulo: "Se...",
      cantor: "Djavan",
      capa: require("../assets/images/se.png"),
      audio: require("../assets/music/djavan-se-instrumental.mp3"),
      letra: require("../assets/lyrics/"),
    },
    {
      id: 11,
      titulo: "Tempo Perdido",
      cantor: "legião Urbana",
      capa: require("../assets/images/tempo-perdido.png"),
      audio: require("../assets/music/legiaourbana-tempoperdido-instrumental.mp3"),
      letra: require("../assets/lyrics/"),
    },
    {
      id: 12,
      titulo: "vagalumes",
      cantor: "Pollo",
      capa: require("../assets/images/vagalumes.png"),
      audio: require("../assets/music/pollo-vagalumes-instrumental.mp3"),
      letra: require("../assets/lyrics/"),
    },
    {
      id: 13,
      titulo: "Velha infâcia",
      cantor: "Tribalistas",
      capa: require("../assets/images/velha-infancia.png"),
      audio: require("../assets/music/tribalistas-velhainfancia-instrumental.mp3"),
      letra: require("../assets/lyrics/"),
    },
  ];
}
